### ISSUE TITLE
crictl should automate load config file from default path.

### ISSUE THREAD

**Issue by yanxuean** [kubernetes-incubator/cri-tools#128]
crictl should automate load config file from default path  no matter wether it is exist in command line args.
Now even though I has writed config file in /etc/crictl.yaml , I must enter "crictl  --config /etc/crictl.yaml".

@Random-Liu

**Comment by feiskyer** [comment]
@yanxuean would you like to file a PR for this?

**Comment by yanxuean** [comment]
@feiskyer   Yes,I would

**Comment by feiskyer** [comment]
@yanxuean thanks
