### ISSUE TITLE
Test for new CRI features

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#131]
We need CRI validation test for new CRI features:

- [x] NoNewPrivilege (May be hard to test) #141
- [x] Mount propagation (easy to test) #142 

We should at least add test for 2).

**Comment by miaoyq** [comment]
@Random-Liu OK, I will do my best to finish this. : )

**Comment by Random-Liu** [comment]
@miaoyq I think only do 2) is good enough for now. :)

**Comment by feiskyer** [comment]
@Random-Liu @miaoyq updated descriptions to include a list of todos.

**Comment by feiskyer** [comment]
@miaoyq Are you working on Mount propagation tests?

**Comment by miaoyq** [comment]
@feiskyer  Yes, have finished the coding, testing now.

**Comment by feiskyer** [comment]
@miaoyq cool. I will work on NoNewPrivilege.

**Comment by feiskyer** [comment]
all done.
