### ISSUE TITLE
Update CRI version for supporting mount propagation 

### ISSUE THREAD

**Issue by miaoyq** [kubernetes-incubator/cri-tools#132]
Related #131 
We should update CRI version for supporting mount propagation.
I tried to update the dependency but always failed.

Maybe I'm not familiar with `godep`, could anyone help to update this please? Thanks!

/cc @Random-Liu @feiskyer

**Comment by Random-Liu** [comment]
@miaoyq Godep is a pain...

**Comment by feiskyer** [comment]
@miaoyq Tried to update godep three days ago, but not finished because some repos (e.g. [kubernetes/api](https://github.com/kubernetes/api)) are out of syncing. Not easy to find the matching versions util https://github.com/kubernetes/test-infra/pull/4134 is fixed and those repos are synced again.

**Comment by Random-Liu** [comment]
@feiskyer Actually we could update, just pick the latest api machinery for now.

**Comment by feiskyer** [comment]
@Random-Liu maybe have a try? you need also find the correct kubernetes version.
