### ISSUE TITLE
CRI Stats

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#138]
Add support for CRI stats in cri-tools. Just query the current container/image stats.

This won't work for now, because there is no container runtime implementing this. However, we're going to implement this in cri-containerd soon.

**Comment by Random-Liu** [comment]
Should update Kubernetes version to include the remote client fix https://github.com/kubernetes/kubernetes/commit/14b32888de6403aa38aedc69086c5a3aff7a4ace.

**Comment by feiskyer** [comment]
@Random-Liu Are you working on this?

**Comment by Random-Liu** [comment]
Nope~

**Comment by yujuhong** [comment]
> Add support for CRI stats in cri-tools. Just query the current container/image stats.

Do you mean the CLI tool?

**Comment by Random-Liu** [comment]
@yujuhong Yeah
