### ISSUE TITLE
Releasing cri-tools v0.2

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-incubator/cri-tools#145]
TODO lists:

- [x] Bump version to v0.2 #146 
- [x] Release with v0.2 tag with release notes
- [x] Update change log

Draft release notes:

cri-tools v0.2 enhances validation testings, improves crictl UX and also fixes several bugs.  It has also updates container runtime interface (CRI) to kubernetes v1.8.

### CRI validation testing (critest)

- [#127] Adds validation tests for supplemental groups
- [#135] [#137] and [#144] Adds validation tests for seccomp 
- [#139] Adds validation tests for sysctls
- [#140] Adds validation tests for AppArmor
- [#141] Adds validation tests for NoNewPrivs
- [#142] Adds validation tests for mount propagation
- [#115] Fixes image validation tests
- [#116] Fixes validation message
- [#126] Fixes sandbox leak in port forward validation tests

### CRI CLI (crictl)

- [#122] Adds support for authenticated image pull
- [#123] Improves crictl UX
- [#124] Adds support for creating sandboxes and containers from yaml
- [#133] Adds timeout support for container stop

**Comment by Random-Liu** [comment]
@feiskyer We should include this in Kubernetes release note.

**Comment by feiskyer** [comment]
@Random-Liu Yep, sent a PR here: https://github.com/kubernetes/features/pull/451
