### ISSUE TITLE
Should SecurityContext information be in the sandbox config

### ISSUE THREAD

**Issue by baude** [kubernetes-incubator/cri-tools#151]
In trying to get criod (https://github.com/kubernetes-incubator/cri-o) to pass the cri-tests, I am seeing an issue where criod expects there to be SecurityContext information in the config.

@Random-Liu Is SecurityContext required to be in the config or is it optional? If the latter, i can fix our code.  If the former, I'm happy to provide a PR if you have some default options you want defined.

@runcom fyi

**Comment by mrunalp** [comment]
@feiskyer ping

**Comment by feiskyer** [comment]
@runcom @mrunalp Sorry for the late response (long holiday here). LinuxContainerSecurityContext is optional (it may be nil), but LinuxPodSandboxSecurityContext is always not nil, see [here](https://github.com/kubernetes/kubernetes/blob/6e2249b78406d66e039d5285a12782119f7cf04c/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go#L135-L141) and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/security_context.go#L29).

**Comment by baude** [comment]
@feiskyer thanks for the response! closing as such
