### ISSUE TITLE
Consider do not validate no exist host path is allowed

### ISSUE THREAD

**Issue by resouer** [kubernetes-incubator/cri-tools#159]
We introduced new test to validate "non exist host path is allowed": https://github.com/kubernetes-incubator/cri-tools/pull/148

But I think though it's consistent with Docker, it may not suitable to apply to all runtimes. For example, runV does not allow no-exist host path since user may mis-spelled the host path. (Not sure what's case for cri-o?)

So I would like to make sure if we really think validate no exist host path is necessary (then we can update runV), otherwise we may remove this test.

cc @Random-Liu @feiskyer @runcom

**Comment by runcom** [comment]
If I'm not wrong, Docker now disallows mounts when the host path doesn't exists so I'm fine adapting cri-o to that (as it's really a bad thing to mkdir on host in that case). What I'm worried about is kube actually which might rely on this behavior

**Comment by resouer** [comment]
> What I'm worried about is kube actually which might rely on this behavior

Can't think of any for now ...

**Comment by runcom** [comment]
I'll check that cause during cri-o e2e kube testing we needed to create the host path iirc

**Comment by feiskyer** [comment]
> What I'm worried about is kube actually which might rely on this behavior

I think kubernetes has already been relying on this. e.g. for network plugins, they will generate network config under `/etc/cni/net.d`, which may be not exist on the nodes.

**Comment by Random-Liu** [comment]
https://github.com/kubernetes/kubernetes/issues/52318

**Comment by resouer** [comment]
@Random-Liu Thanks for referring. Let's move discuss there.

But as we have not determined the expected behavior, shouldn't we delete/disable the existing hostPath validation test?

**Comment by feiskyer** [comment]
> While as we have not determined the expected behavior, shouldn't we remove or disable the existing hostPath validation test

I'm ok of skipping the test util kubernetes/kubernetes#52318 is defined explicitly.

**Comment by Random-Liu** [comment]
@resouer Given the API change https://github.com/euank/kubernetes/blob/a0739bf062379ebb9e7a17b3323a0fa208cb8c8a/docs/proposals/volume-hostpath-qualifiers.md, I think we are moving off relying on this. Even though Kubernetes is relying on this today, when HostPath type is `HostPathUnset`.

I'm fine with skipping it given it is a behavior we are planning to move off.

**Comment by resouer** [comment]
Thanks for fix! Closed, we can continue discuss in main repo.
