### ISSUE TITLE
A simple document for CRICTL v1.0

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#160]
https://docs.google.com/document/d/1BbohEUHwwodCSVltWXs3nvCazZ7OJ4MwjA_SFBT8GAQ/edit?usp=sharing

Feel free to comment.

**Comment by feiskyer** [comment]
@Random-Liu thanks for excellent document

**Comment by feiskyer** [comment]
LGTM in general. @Random-Liu Do you have suggestion of crictl UX? e.g. do we need to rename current subcommands?

**Comment by feiskyer** [comment]
@Random-Liu All done?
