### ISSUE TITLE
crictl should consume extra debug information from CRI

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#166]
We added the verbose option in CRI to make it possible for container runtime to provide more information for debug. kubernetes/kubernetes#53965

`crictl` should properly consume these information in `inspect`, `inspecti`, `inspects` and `info`.

**Comment by miaoyq** [comment]
I will work on this.

**Comment by miaoyq** [comment]
@Random-Liu @feiskyer  Could we output information for "inspect", "inspecti" and "inspects" only in json or yaml format?
