### ISSUE TITLE
More flags for `crictl ps`.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#179]
- [x] `-a, --all`: Show running containers by default, and with `-a` show all containers.
- [ ] `-s, --size`: Show writable layer size of each container. I don't think we need virtual size now. 
- [x] `-l, --latest`: Show latest created container
- [x] `-n, --last int`: Show n last created containers.
- [x] `--no-trunc`: Not truncate id.

**Comment by Random-Liu** [comment]
And we could consider add similar flags for sandbox.

**Comment by weiwei04** [comment]
consider return sorted crictl ps result like docker ps?

**Comment by Random-Liu** [comment]
@weiwei04 The result is already sorted. https://github.com/kubernetes-incubator/cri-tools/pull/171

**Comment by Random-Liu** [comment]
- [ ] `--no-trunc`: For `crictl images`.
- [ ] `-l`: For `crictl sandboxes`.
- [ ] `-n`: For `crictl sandboxes`
- [ ] `--no-trunc`: For `crictl sandboxes`.
