### ISSUE TITLE
Runtime Endpoint configuration consolidation discussion.

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-incubator/cri-tools#215]
Currently kubernetes supports `RUNTIME=remote CONTAINER_RUNTIME_ENDPOINT=/var/run/cri-containerd.sock`, and crictl supports 3 ways to set it.. that are different:

cli option or env variable:
```
   --runtime-endpoint value, -r value  Endpoint of CRI container runtime service (default: "/var/run/dockershim.sock") [$CRI_RUNTIME_ENDPOINT]
```
or: 
```
  --config value, -c value      Location of the client config file (default: "/etc/crictl.yaml") [$CRI_CONFIG_FILE]
```
where the yaml includes: `runtime-endpoint: /var/run/cri-containerd.sock`

Further there is an optional  
```
 --image-endpoint value, -i value    Endpoint of CRI image manager service [$CRI_IMAGE_ENDPOINT]
```

Should we do some consolidation here? Do we need both `CONTAINER_RUNTIME_ENDPOINT` and `CRI_RUNTIME_ENDPOINT`?

Does anyone foresee using the image endpoint option in the near future?

If not is `CRI_RUNTIME_ENDPOINT` not repetitive? Translates to Container Runtime Interface Runtime Endpoint.

Should `runtime-endpoint` be `container-runtime-endpoint` or `cri-runtime-endpoint`?

**Comment by mikebrow** [comment]
@Random-Liu @mrunalp thoughts?

**Comment by feiskyer** [comment]
@mikebrow I'm ok with crictl using same env name `CONTAINER_RUNTIME_ENDPOINT` and `CONTAINER_IMAGE_ENDPOINT`.  

> Should runtime-endpoint be container-runtime-endpoint or cri-runtime-endpoint?

I think all is ok and clear. critl doesn't support other endpoints besides CRI. And `runtime-endpoint` is short and could be typed easily than others.
