### ISSUE TITLE
jsonlog package not found

### ISSUE THREAD

**Issue by Davidrjx** [kubernetes-incubator/cri-tools#220]
when installing cri-tools, console reports error below:
cri-tools-0.2/cmd/crictl/logs.go:30:2: cannot find package "github.com/docker/docker/pkg/jsonlog" which already was not accessible.

**Comment by feiskyer** [comment]
@Davidrjx How did you install cri-tools? You could install it by simply `go get`, e.g.

```
go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
go get github.com/kubernetes-incubator/cri-tools/cmd/critest
```

**Comment by Davidrjx** [comment]
@feiskyer hi, paths above seems unavailable

**Comment by feiskyer** [comment]
@Davidrjx Yep, decencies in Go are all in vendors.

**Comment by Davidrjx** [comment]
@feiskyer however, doing `go install cri-tools source` just outputs error above as logs.go failed to import jsonlog

**Comment by Davidrjx** [comment]
actually, i am not very clear about why two instructions not unavailable , still reports can not find package.

**Comment by feiskyer** [comment]
You should first change into cri-tools path first, e.g. 

```
cd $GOPATH/src/github.com/kubernetes-incubator/cri-tools
make
```

**Comment by Davidrjx** [comment]
thanks.later, i will retry and hope it is viable

**Comment by feiskyer** [comment]
I'm closing this issue. @Davidrjx Please feel free to reopen if you still have problems.
