### ISSUE TITLE
Received "malformed HTTP response..." error when performing validation in streaming

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes-incubator/cri-tools#221]
I tried  "critest validation" with docker, most of the cases works well, but all of the three cases in file "streaming.go" got failed:
```
Summarizing 3 Failures:

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support exec [Conformance] 
/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:150

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward [Conformance] 
/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:255

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support attach [Conformance] 
/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:220

Ran 57 of 58 Specs in 117.388 seconds
FAIL! -- 54 Passed | 3 Failed | 0 Pending | 1 Skipped --- FAIL: TestE2ECRI (117.39s)
```
And error message in format of:  *"error sending request: Post http://127.0.0.1:10250/cri/attach/1UW_1ko5: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"*

OS: 
Linux version 4.13.0-1002-gcp (buildd@lgw01-amd64-060) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)) #5-Ubuntu SMP Tue Dec 5 13:20:17 UTC 2017

Docker:
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by feiskyer** [comment]
@lichuqiang Which version of kubelet and cri-tools are you using?  Their versions should be matched ( see [releases](https://github.com/kubernetes-incubator/cri-tools/releases) for version info)

**Comment by lichuqiang** [comment]
I got cri-tools with `go get` commend as it suggested in doc, and the tool's version is `critest version 1.0.0-alpha.0`;
I tried the test with current code in master branch of Kubernetes, would try with exactly v1.9 code later.

**Comment by lichuqiang** [comment]
Same error still exists after trying with v1.9 kubelet.

**Comment by feiskyer** [comment]
@Random-Liu Did you encounter this problem with cri-containerd?

**Comment by feiskyer** [comment]
@lichuqiang Verified there is no such problem in my settings. The steps of mine:

```sh
# Start dockershim first
nohup /usr/local/bin/kubelet --v=3 --logtostderr --experimental-dockershim &

go get github.com/kubernetes-incubator/cri-tools/cmd/critest
critest validation
```

Could you share the details of your steps?

**Comment by lichuqiang** [comment]
@feiskyer Thanks a lot! I previously started kubelet with params in `local-up`; and it works after I tried to start with options you provided above. Seems the `validation` task was influenced by some params.

**Comment by lichuqiang** [comment]
Closing the issue since the problem is resolved and it's not a bug :)
