### ISSUE TITLE
CRI log parser improvements

### ISSUE THREAD

**Issue by jreyeshdez** [kubernetes-incubator/cri-tools#228]
The function [`parseCRILog`](https://github.com/kubernetes-incubator/cri-tools/blob/bb2c5293bfa6dd5207e1ce3f2d5a32b09f1cc549/pkg/validate/container.go#L431) might have some room to introduce some changes to make it more performance as calling `strings.Fields` only once at the beginning of the method should be more efficient. I think it could even be more efficient if we use `strings.SplitN` as I think we do not need to split the whole message.

Likewise, it would be good to check the resulting array to make sure it has the correct or the expected size and avoid errors when accessing different fields, for example `2016-10-06T00:17:10.113242941Z stdout` as an input would cause panic.

If we use `strings.SplitN` then we wouldn't need `strings.Join`.

**Comment by feiskyer** [comment]
@Random-Liu What do you think about this?

**Comment by Random-Liu** [comment]
> The function parseCRILog might have some room to introduce some changes to make it more performance as calling strings.Fields only once at the beginning of the method should be more efficient. I think it could even be more efficient if we use strings.SplitN as I think we do not need to split the whole message.

That is util function used in the validation test, and performance shouldn't be a problem there. But feel free to send a PR to improve it. :) Thanks!

**Comment by Random-Liu** [comment]
I think we can close this one.
