### ISSUE TITLE
cri-tools (at least crictl) should follow kubernetes releases

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/cri-tools#235]
Basically, this repo should at least provide branches for supported kube releases like https://github.com/kubernetes/apiserver (you can see it has branches for kube releases supported). Or tags, I don't have any strong opinion but we should align to kubernetes in some way.

@mrunalp PTAL

**Comment by feiskyer** [comment]
+1 

Currently, v0.2 is for 1.8 and v1.0.0-alpha.0 for 1.9. We could make them into different branches.

**Comment by feiskyer** [comment]
Release branches created.
