### ISSUE TITLE
Upgrade to v1alpha2

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#236]
CRI made a breaking change, the version is updated from `v1alpha1` to `v1alpha2`. https://github.com/kubernetes/kubernetes/pull/58973

We should upgrade to v1alpha2 and also needs to mention this in release note.

**Comment by feiskyer** [comment]
Has been solved in #238. close the issue.

**Comment by Random-Liu** [comment]
@feiskyer We shouldn't close this. We need to document this before release. And we can only close after that.

**Comment by feiskyer** [comment]
v1.0.0-beta.0 released.
