### ISSUE TITLE
`CONTAINER` pid namespace CRI validation.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#237]
We should add test case for `CONTAINER` pid namespace.

@verb @feiskyer @yujuhong

**Comment by feiskyer** [comment]
@Random-Liu Are you working on this?

**Comment by Random-Liu** [comment]
Nope :)

**Comment by mrunalp** [comment]
@umohnani can work on this.

**Comment by umohnani8** [comment]
Yup, will work on this.

**Comment by Random-Liu** [comment]
@mrunalp @umohnani8 Thanks a lot! :)

I think we can close this one now. :)
