### ISSUE TITLE
Ubuntu LTS 16.04 Build Failure: cannot find package "context" 

### ISSUE THREAD

**Issue by ecarew** [kubernetes-incubator/cri-tools#249]
make all, and make crictl both fail when trying to make, and install this package. The issue is that package context is missing. Would like a workaround that doesn't involve installing a new version of go on an LTS Ubuntu.

**Comment by Random-Liu** [comment]
@ecarew I think your golang version is too old. :(
If you really don't want to install new golang, use a golang container to build the binary.

**Comment by feiskyer** [comment]
Yep, Go 1.9 or above is required to build crictl. You could also download crictl from release page https://github.com/kubernetes-incubator/cri-tools/releases/tag/v1.0.0-alpha.0.

**Comment by feiskyer** [comment]
@ecarew Feel free to reopen it if you still have issues.
