### ISSUE TITLE
I wonder how to setup it on ubuntu16.04 for kubernetes1.9

### ISSUE THREAD

**Issue by airforce011** [kubernetes-incubator/cri-tools#251]
hi, 
when i install k8s 1.9 with kubeadm,  i got a warning:

[WARNING FileExisting-crictl]: crictl not found in system path

it is said that installing the app can remove the warning. 
So, I would be very grateful if anyone could tell me how to install it on ubuntu for k8s?

**Comment by Random-Liu** [comment]
```
$ wget -O crictl https://storage.googleapis.com/kubernetes-release/crictl/crictl-v1.0.0-alpha.0-linux-amd64
$ chmod +x crictl
```
We should document this somewhere.

**Comment by feiskyer** [comment]
Also uploaded compiled files in release page: https://github.com/kubernetes-incubator/cri-tools/releases/tag/v1.0.0-alpha.0
