### ISSUE TITLE
I am getting unknown service runtime.v1alpha2.RuntimeService with version 1.0.0-alpha.0

### ISSUE THREAD

**Issue by indrayam** [kubernetes-incubator/cri-tools#254]
I am running a Kubernetes cluster on DigitalOcean and GKE. 

Using CRI CTL version 1.0.0-alpha.0 gives errors as shown in the attachment:

![image](https://user-images.githubusercontent.com/6824/36396270-274820e0-158b-11e8-8b30-d5c951c9126e.png)

As you can see, I do not seem to get this error with crictl version 0.2.0. Not sure if this is a bug or an issue with my installation.

FYI: I am running Kubernetes version 1.9.x

**Comment by Random-Liu** [comment]
@indrayam This is a known issue. CRI has made a breaking change this quarter, and the version is upgraded to v1alpha2.

This means that old crictl won't work with Kubernetes 1.10. We'll document that in the release note.
See https://github.com/kubernetes-incubator/cri-tools/issues/236

We are going to support backward compatibility in CRI after CRI is beta.

**Comment by indrayam** [comment]
Thanks, @Random-Liu. Good to know.

**Comment by Random-Liu** [comment]
@indrayam Thanks the reporting this.

I'll close this issue then. :)
