### ISSUE TITLE
getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

### ISSUE THREAD

**Issue by adelton** [kubernetes-incubator/cri-tools#259]
I have `cri-o-1.9.7-2.gita98f9c9.fc27.x86_64` package installed on Fedora with `crio.service` up and running.

I attempt to debug it with `crictl` which I've got with

```
go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
```

Running `crictl`, I get

```
# /root/go/bin/crictl --runtime-endpoint=/var/run/crio/crio.sock info
FATA[0000] getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService 
```

**Comment by feiskyer** [comment]
@adelton Master branch only supports v1.10 now. Could you download crictl from https://github.com/kubernetes-incubator/cri-tools/releases/tag/v1.0.0-alpha.0 or build one from release-1.9 branch?

**Comment by adelton** [comment]
Building from `release-1.9` branch works, thanks.

Would it make sense to update the matrix at https://github.com/kubernetes-incubator/cri-tools#current-status to make it clearer that master does not work with 1.9, and ideally also mention the existence of the Kubernetes-versioned branches? The line

| 1.9.X | v1.0.0-alpha.0 |

sort of suggest that the latest version of `cri-tools` is usable with 1.9.

**Comment by feiskyer** [comment]
@adelton Thanks of advice, will file a PR to address this.

**Comment by vasu81in** [comment]
I invoked runtime service from my library to talk to dockershim.sock just like below

func getRuntimeClient(context *cli.Context) error {
	// Set up a connection to the server.
	var err error
	conn, err = getRuntimeClientConnection(context)
	if err != nil {
		return fmt.Errorf("failed to connect: %v", err)
	}
	runtimeClient = pb.NewRuntimeServiceClient(conn)
	return nil
}

and I get the following error; Can anyone explain if we can write a standalone library to talk to docker CRI shim using the runtime service handle? I am not sure what this error means.

E0311 05:25:55.313302       8 remote_runtime.go:262] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
[] failed to list all containers: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

**Comment by feiskyer** [comment]
@adelton Which kubernetes version are you running? CRI v1alpha2 is introduced in v1.10.0-beta.1.

**Comment by adelton** [comment]
I don't have any Kubernetes running, I just try to use CRI-O via `crictl` (to debug some other issue).

**Comment by vasu81in** [comment]
@feiskyer I upgraded to v1.10 beta and it worked. Thanks for the help!

**Comment by feiskyer** [comment]
@vasu81in Cool 👍
