### ISSUE TITLE
crictl exec fails with could not find container

### ISSUE THREAD

**Issue by adelton** [kubernetes-incubator/cri-tools#263]
I have created container (via Kubernetes) and I see it running, I can inspect it, but attempt to exec a process in that container cannot find the container:

```
# crictl inspect 19dbbad284433 | head
{
  "status": {
    "id": "19dbbad284433367b8dd659d14712ab9eea2f06941265affb3d0c3f45fe5c462",
    "metadata": {
      "attempt": 3,
      "name": "nginx"
    },
    "state": "CONTAINER_RUNNING",
    "createdAt": "2018-03-01T09:04:18.411076634-05:00",
    "startedAt": "2018-03-01T09:04:18.459753983-05:00",
[root@cloud-qe-21 cri-tools]# crictl exec 19dbbad284433 date
FATA[0000] execing command in container failed: Internal error occurred: error executing command in container: could not find container "19dbbad284433" 
```

and `crio` logs

```
ERROR: logging before flag.Parse: E0301 09:19:49.139250    1161 exec.go:71] error executing command in container: could not find container "19dbbad284433"
```

I see the same problem both with `cri-o` and `cri-tools` built from their respective masters

```
# crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.10.0-dev
RuntimeApiVersion:  v1alpha1
```

and with `cri-tools` built from `release-1.9` branch against `cri-o-1.9.1-1.gitb066a83.fc27.x86_64`

```
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.9.1
RuntimeApiVersion:  v1alpha1
```

**Comment by feiskyer** [comment]
@adelton Tried with dockershim, there is no such problem. Could try with full container id `19dbbad284433367b8dd659d14712ab9eea2f06941265affb3d0c3f45fe5c462`?

**Comment by adelton** [comment]
With full container id, things work.

**Comment by lcfang** [comment]
@adelton can you try to use `docker exec` if your runtime is docker?

**Comment by adelton** [comment]
I'd expect `docker exec` to work with docker runtime but what I'm testing here is CRI-O runtime.

**Comment by feiskyer** [comment]
@adelton So it this cri-o problem, seems it doesn't support truncated container id

**Comment by adelton** [comment]
It's well possible ... but how come `crictl inspect` works with truncated ids just fine?

**Comment by Random-Liu** [comment]
@adelton The truncated id support is on the server side. This means that cri-o doesn't support truncated id properly for exec, I guess.

**Comment by mrunalp** [comment]
@adelton I have created https://github.com/kubernetes-incubator/cri-o/pull/1451 to fix this.

**Comment by feiskyer** [comment]
@mrunalp Cool. Let's close this issue then
