### ISSUE TITLE
After crictl create, crictl ps does not show CONTAINER_CREATED container

### ISSUE THREAD

**Issue by adelton** [kubernetes-incubator/cri-tools#266]
I follow https://github.com/kubernetes-incubator/cri-tools/blob/master/docs/crictl.md. I create pod sandbox with `crictl runp` and then I create container with `crictl create`. The document shows

```
# crictl create e1c83b0b8d481d4af8ba98d5f7812577fc175a37b10dc824335951f52addbb4e container-config.json podsandbox-config.json
0a2c761303163f2acaaeaee07d2ba143ee4cea7e3bde3d32190e2a36525c8a05
# crictl ps
CONTAINER ID                                                       CREATED             STATE               NAME
0a2c761303163f2acaaeaee07d2ba143ee4cea7e3bde3d32190e2a36525c8a05   1 minutes ago       CONTAINER_CREATED   busybox
```

However, for me `crictl ps` does not show the container, even if with `-a` I can see it:

```
# crictl ps
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT
# crictl ps -a
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT
34cb02d40a9e2       docker.io/busybox   4 minutes ago       CONTAINER_CREATED   busybox             0
```

Either it's OK that `CONTAINER_CREATED` containers are not listed and then the document should be amended to suggest `crictl ps -a`, or the container should be listed and this is a bug.

**Comment by adelton** [comment]
This is with `cri-tools` master and CRI-O built from master, with `crictl` configured with

```
# echo 'runtime-endpoint: unix:///var/run/crio/crio.sock' > /etc/crictl.yaml
```

**Comment by Random-Liu** [comment]
Yeah we should update the document to reflect the change.
This is working as intended.

**Comment by feiskyer** [comment]
@adelton Would like filing a PR to add documents for this?

**Comment by adelton** [comment]
I've filed https://github.com/kubernetes-incubator/cri-tools/pull/270 now.

**Comment by feiskyer** [comment]
@adelton Thanks, LGTM
