### ISSUE TITLE
Make test-images multiarch

### ISSUE THREAD

**Issue by nitkon** [kubernetes-incubator/cri-tools#287]
The "make test-cri" command fails on non-x86 architecture because of the images created from image-test and image-user directory are not multi-arch. If these images are made multi-arch when built and pushed, then it would be easy to test on other non-x86 architectures as well

**Comment by Random-Liu** [comment]
@nitkon Can we do something like this? https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go#L103

**Comment by nitkon** [comment]
Point 2 mentioned above is tracked here as well. [Issue](https://github.com/kubernetes/kubernetes/issues/63057)

**Comment by feiskyer** [comment]
@Random-Liu Could you help to push the multi-arch images for both pause and busybox?

**Comment by nitkon** [comment]
@feiskyer : The pause image that is pushed is now multi-arch. See [Issue](https://github.com/kubernetes/kubernetes/issues/63057). Also the busybox image now used in the test-cases is multi-arch. See [PR](https://github.com/kubernetes-incubator/cri-tools/pull/290#event-1590553277).  

We need to build the [image-test-*](https://github.com/kubernetes-incubator/cri-tools/tree/master/images/image-test)  images on x86(already done) and ppc64le(I can do it) and any other arch if needed and push these images into gcr.io/cri-tools and then use [manifest-tool](https://github.com/estesp/manifest-tool) to create a fat-manifest.

**Comment by feiskyer** [comment]
@nitkon Yep, you are right. Could you update PR #292 to build multi-arch images? [here](https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile) is a Makefile reference

**Comment by nitkon** [comment]
@feiskyer: Yes I will. However, I have noticed that cross built images fail to unpack when pulled. Hence it will still fail on ppc64le arch. Here is the reference [Issue](https://github.com/containerd/containerd/issues/2312) 

Solution: 
Option 1: Fix the [issue](https://github.com/containerd/containerd/issues/2312)
Option 2: Build the test-images on x86 and on ppc64le(not cross-built, I can provide), push them to a repo, create a fat manifest out of it. So that when "crictl pull" these test-images they don't fail to unpack.

**Comment by feiskyer** [comment]
> Option 1: Fix the issue

@nitkon Seems it is a containerd issue?

**Comment by nitkon** [comment]
@feiskyer : This [PR](https://github.com/kubernetes-incubator/cri-tools/pull/300) makes the test images in image-user multi-arch. 

>Seems it is a containerd issue?

Seems like. Hence we will be using fat manifest/manifest list/multi-arch images for test images.

**Comment by nitkon** [comment]
@feiskyer @Random-Liu : When are we planning to push all these images?

**Comment by feiskyer** [comment]
I have no access to the gcr registry.  @Random-Liu Could you help to push those images?

**Comment by nitkon** [comment]
@feiskyer: I realize that you do not have the access to the gcr repo. How do we get this done then before any other changes break my PRs?  @Random-Liu could you help?
