### ISSUE TITLE
Trap `Ctrl+C`.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#288]
`crictl` behavior:
```console
e2e-test-lantaol-master ~ # crictl exec -i -t 8cbe40af73606 /bin/sh
# sleep 1000
sleep 1000
^C
e2e-test-lantaol-master ~ #
```

`docker exec` behavior:
```console
e2e-test-lantaol-master ~ # docker exec -it 2ccc5ed91407 /bin/sh
# sleep 1000
^C
# exit
e2e-test-lantaol-master ~ #
```

**Comment by chuckha** [comment]
This seems like a pretty involved ticket. I was reading up on how `kubectl exec` does this and it sets up and manages its own ptys. It [captures interrupts](https://github.com/kubernetes/kubernetes/blob/6d3f5b75f56323888701da27a48bc4c0f52ab106/pkg/kubectl/util/term/term.go#L103), but does [depend on the docker library](https://github.com/kubernetes/kubernetes/blob/6d3f5b75f56323888701da27a48bc4c0f52ab106/pkg/kubectl/util/term/term.go#L23)

Did you have any thoughts on how you'd like this to be implemented?

**Comment by Random-Liu** [comment]
@chuckha I think it is fine to use a docker library. :) Would you like to send out a PR?

BTW, this can cause exec process leakage.
