### ISSUE TITLE
Create a release-1.10 branch

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-tools#294]
@Random-Liu @feiskyer @yujuhong wdyt?

cc: @umohnani8

**Comment by feiskyer** [comment]
Yep definitely. @mrunalp Would you create the branch or let me do it?

**Comment by mrunalp** [comment]
@feiskyer I tried but I don't have enough right. Could you do it? Thanks!

**Comment by feiskyer** [comment]
Branch release-1.10 created and #295 created for CI

**Comment by umohnani8** [comment]
Awesome, thanks @feiskyer!

**Comment by feiskyer** [comment]
Branch created.

/close
