### ISSUE TITLE
Release and versioning

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#297]
The current version schema is pretty confusing.

We have branch which follows Kubernetes release `release-1.10`, `release-1.11` etc.

We also have a version `v1.0.0-alpha.0`, `v1.0.0-beta.0` etc.

I think `critest` and `crictl` have different CRI version compatibility requirement:
* `critest` is used to test all CRI features. A new field or slightly behavior change in CRI usually means a new corresponding CRI validation test, but doesn't necessarily mean a CRI version update, e.g. `RunAsGroup`. So I think `critest` version has to follow Kubernetes version.
* `crictl` should be able to work with any CRI container runtime, as long as the CRI version matches. There might be field ignored or defaulted because of version skew, but things should not break. So I think `crictl` version can potentially follow CRI version in the future.

For now, given that CRI version schema is still not clear yet, let's graduate cri-tools to GA, and start following Kubernetes version for both `critest` and `crictl`.

@yujuhong @feiskyer @mrunalp @runcom @mikebrow

**Comment by runcom** [comment]
sounds good to me

**Comment by vrothberg** [comment]
:+1: Highly appreciated!

**Comment by runcom** [comment]
> For now, given that CRI version schema is still not clear yet, let's graduate cri-tools to GA, and start following Kubernetes version for both critest and crictl.

what's process for graduation though? :thinking:

**Comment by xlgao-zju** [comment]
Cool! And I'd like to do some contribution in my spare time. 😆

**Comment by feiskyer** [comment]
+1

**Comment by Random-Liu** [comment]
> what's process for graduation though? 

> Cool! And I'd like to do some contribution in my spare time. 

Thanks! A lot of things need help. :)

**Comment by Random-Liu** [comment]
@feiskyer Do you think for the coming version, should it be v1.11.0 or v1.0.0?

**Comment by feiskyer** [comment]
The version should match CRI version ideally, but CRI version schema is still not clear yet as you said. I also think it's better to follow kubernetes versions, e.g. v1.11.X for kubernetes v1.11.

**Comment by runcom** [comment]
+1 to follow kube major.minor

**Comment by mrunalp** [comment]
:+1:

**Comment by feiskyer** [comment]
@luxas Yep, the next release is GA and will be versioned as v1.11.0.

**Comment by jberkus** [comment]
is there any possibility of getting the next version released *ahead* of Kubernetes 1.11?  This would really help with testing, etc.
