### ISSUE TITLE
Proposal: Add a cli 

### ISSUE THREAD

**Issue by xlgao-zju** [kubernetes-incubator/cri-tools#3]
I think we can use pkg `github.com/urfave/cli` which is used in `cri-o` too.

The cli can be used when we build CRI-cli. 

And how about making the e2e test as a subcommand in CRI-cli? Like `cri test` or something? Or we will build two cli, one for e2e test, the other for CRI-cli?

cc @feiskyer @Random-Liu @yujuhong

**Comment by feiskyer** [comment]
I think it's ok of making test binary a subcommand.  Alternatively, we can split test to another CLI as proposed:

- crictl: CLI for kubelet CRI.
- critest: validation test suites for kubelet CRI.

**Comment by xlgao-zju** [comment]
If we split test to another CLI, will it be difficult to support `go get`? Since we will have two `main()`.

**Comment by feiskyer** [comment]
No, they will be in different packages

**Comment by xlgao-zju** [comment]
yes, that makes sense.
