### ISSUE TITLE
crictl exec: cannot parse command args

### ISSUE THREAD

**Issue by vrothberg** [kubernetes-incubator/cri-tools#305]
`crictl exec` isn't able to parse arguments of a specified command starting the "-" as they're interpreted as flags of `crictl exec` instead of just passing them to the command.

Version: Tried with latest crictl (i.e., commit 7f1936faf76e).

Reproduce with `crictl exec ID ls -la`
```
FATA[0000] flag provided but not defined: -la 
```

**Comment by vrothberg** [comment]
The problem is actually a bit worse: when doing something like `crictl exec ID ls -i`, the command will be executed interactively due to the `-i` argument. I think we need to move away from `urfave/cli`, which doesn't seem to support such use-cases.

**Comment by vrothberg** [comment]
> I think we need to move away from urfave/cli, which doesn't seem to support such use-cases.

I have to correct my statement. Vendoring in a more recent version of urfave/cli did the trick, see #306.

**Comment by vrothberg** [comment]
@feiskyer Can we add the two patches into the `release-1.10` branch? Soon, we'll update to K8s 1.10, where we need those change for crictl. Is there a specific workflow in the cri-tools project for backports?

**Comment by feiskyer** [comment]
@vrothberg Could you create a cherry pick PR for release-1.10?

**Comment by vrothberg** [comment]
> @vrothberg Could you create a cherry pick PR for release-1.10?

Sure. I'll prepare one and ping you there. Thanks for the quick reply!
