### ISSUE TITLE
images retrieve

### ISSUE THREAD

**Issue by cucushift** [kubernetes-incubator/cri-tools#307]
hi,folks i have a doubt about `crictl images`,why some local images can only retrieve by `crictl images`,and `docker images` or `atomic images list` can't find them.Don't all imags respect the `OCI Image Format Specification`  ? Is this because of **storage**? thanks a lot.

**Comment by feiskyer** [comment]
critl get images from CRI. Which runtime are you using? I suspect there's something wrong within the container runtime.

**Comment by cucushift** [comment]
@feiskyer thanks for respond,my container runtime is cri-o.
