### ISSUE TITLE
Provide sha256 of release files

### ISSUE THREAD

**Issue by chuckha** [kubernetes-incubator/cri-tools#322]
sig-cluster-lifecycle is [planning on packaging `crictl` with our deb/rpm packages](https://github.com/kubernetes/kubeadm/issues/811) which requires us to add it to the kubernetes bazel [WORKSPACE](https://github.com/kubernetes/kubernetes/blob/master/build/root/WORKSPACE) using the http_file rule. It's an optional parameter but it's nice to have!

**Comment by Random-Liu** [comment]
@chuckha Sure.

@feiskyer Let's update the release script to output sha256, and add it in release note?

**Comment by feiskyer** [comment]
Sure

**Comment by feiskyer** [comment]
Created PR #323 and also updated sha256 for v1.0.0-beta.1

**Comment by chuckha** [comment]
Thank you so much!
