### ISSUE TITLE
consider using underscores instead of dashes in version number

### ISSUE THREAD

**Issue by chuckha** [kubernetes-incubator/cri-tools#324]
In the process of building an RPM for crictl I ran into an issue using the version number `1.0.0-beta.1` because of the dash. 

> The version number is normally taken verbatim from the package's version. The only restriction placed on the version is that it cannot contain a dash "-".  -- [Appendix A. Format of the RPM File][ref]

[ref]: http://ftp.rpm.org/max-rpm/ch-rpm-file-format.html

I'm replacing the `-` with an underscore for now when writing out the version file and hope to not use beta releases in the future so I don't think it will be a huge deal to have a slight mismatch between the rpm/deb version (since both are generated from the same version file) and what `crictl version` prints, especially as this moves to 1.0.0 and we stop packaging beta releases.

xref: https://github.com/kubernetes/kubeadm/issues/811

**Comment by feiskyer** [comment]
@chuckha The version format is following kubenretes. Have you also built versions for kubernetes (e.g. v1.11.0-beta.2) with the same issue?

**Comment by chuckha** [comment]
I'm looking into how kubernetes rpms deal with the `-` say in `rc`s or `beta`s. I think the problem is that it looks like v1.0.0-beta.1 is going to be the release that works with k8s 1.11. Since v1.0.0-beta.0 tracks 1.10.

I would have expected something like v1.0 => 1.9; 1.1 => 1.10 etc, not beta releases. 

It's ok though, the result is a minor mismatch of package names/versions.

Is 1.0.0 going to be the release for k8s 1.12?

**Comment by feiskyer** [comment]
v1.11.0 will be versioned together with k8s 1.11. (refer https://github.com/kubernetes-incubator/cri-tools/issues/297)

**Comment by chuckha** [comment]
ah ok, thank you !
