### ISSUE TITLE
crictl-exec: arg-parsing bug

### ISSUE THREAD

**Issue by vrothberg** [kubernetes-incubator/cri-tools#335]
`urfave/cli` has a bug in how short-options are parsed. The problem is that the parser does not only transform the program's options (e.g., `-abc` -> `-a -b -c`) but also undefined ones and even arguments (see a description here https://github.com/projectatomic/libpod/issues/714). For Podman, we are currently vendoring a patched version from `github.com/vrothberg/cli` (see https://github.com/projectatomic/libpod/pull/1046). Feel free to vendor that as well if you want the bug fixed. `urfave/cli` seems to be orphaned at the moment, but once it's back in maintenance we revendor it.

**Comment by feiskyer** [comment]
@vrothberg thanks for reporting the bug. Is there any issues or PRs on urfave/cli for tracking the issue?

**Comment by vrothberg** [comment]
@feiskyer Sorry, I entirely missed posting the PR for urfave/cli as well: https://github.com/urfave/cli/pull/758

**Comment by feiskyer** [comment]
@vrothberg thanks
