### ISSUE TITLE
crictl can't pull images with proxy

### ISSUE THREAD

**Issue by hmtai** [kubernetes-incubator/cri-tools#336]
when I pull an image with crictl, like
```
crictl pull docker.io/library/alpine:latest
```
There was an error:
```
FATA[0030] pulling image failed: rpc error: code = Unknown desc = failed to resolve image "docker.io/library/alpine:latest": failed to do request: Head https://registry-1.docker.io/v2/library/alpine/manifests/latest: dial tcp 35.169.231.249:443: i/o timeout
```
crictl version info:
```
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.1.0
RuntimeApiVersion:  v1alpha2
```
I have already exported http_proxy on my machine, and other commands like wget, curl works well, ctr also woks well, like:
```
ctr images pull docker.io/library/alpine:latest
```

**Comment by Random-Liu** [comment]
`ctr` does use golang `HTTP_PROXY`. https://github.com/containerd/containerd/blob/master/cmd/ctr/commands/resolver.go#L88

For crictl we can't support it on the client side, because CRI doesn't have a proxy parameter. However, we can support `containerd` daemon level `HTTP_PROXY` config.

I'll do it.

**Comment by feiskyer** [comment]
> For crictl we can't support it on the client side, because CRI doesn't have a proxy parameter. However, we can support containerd daemon level HTTP_PROXY config.

Agreed. crictl doesn't need proxy because it only talks to local runtime's unix socket while the image is actually pulled in runtimes.

**Comment by hmtai** [comment]
@Random-Liu Thanks a lot:)

**Comment by Random-Liu** [comment]
Close.

**Comment by sipasing** [comment]
Is there any update on this or any PR that fixed this ?

**Comment by sipasing** [comment]
Never mind.. setting containerd service file as mentioned here https://github.com/containerd/cri/issues/834 worked for me.
