### ISSUE TITLE
crictl should add command for importing images from file

### ISSUE THREAD

**Issue by miaoshixuan** [kubernetes-incubator/cri-tools#358]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
I run kubernetes with containerd as container runtime and all node could not access network to pull images. It should be possible to load images for file just like docker

**Comment by feiskyer** [comment]
crictl only talks CRI, while import images from a file is not part of CRI. If the runtime itself supports this, you can use that for your cases.

**Comment by miaoshixuan** [comment]
got it ,thanks
