### ISSUE TITLE
Cannot unmarshal number into Go struct field LinuxContainerSecurityContext.run_as_user of type v1alpha2.Int64Value

### ISSUE THREAD

**Issue by zerda** [kubernetes-incubator/cri-tools#371]
`crictl` version: 1.11.1

When creating container from JSON file, I have got this error.
`FATA[0000] Creating container failed: json: cannot unmarshal number into Go struct field LinuxContainerSecurityContext.run_as_user of type v1alpha2.Int64Value`

```bash
crictl --debug create 2f00 container-config.json sandbox-config.json
```

`container-config.json` file content
```json
{
  "metadata": {
      "name": "busybox"
  },
  "image":{
      "image": "busybox"
  },
  "command": [
      "top"
  ],
  "linux": {
      "security_context": {
          "run_as_user": 65534
      }
  }
}
```

I have tried with `"run_as_user": "65534"` but no lucky. How do I define an Int64 value in JSON file ?

Thanks.

**Comment by feiskyer** [comment]
run_as_user is `Int64Value`, not int64. Please use examples below:

```json
 "linux": {
      "security_context": {
          "run_as_user": {
                "value": 65534
           }
      }
  }
```

**Comment by zerda** [comment]
My mistake :satisfied: thank you for your help.
