### ISSUE TITLE
--ginkgo-flags not working as expected

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-incubator/cri-tools#67]
e.g. to run a single test:

```
critest --ginkgo-flags=-focus='runtime should support stopping container'
```

but critest actually running 21 tests.

**Comment by xlgao-zju** [comment]
seem the flag only gets the first word. e.g. `critest -g=-focus="stopping container"` will run `stopping pod` and `stopping container` test

**Comment by xlgao-zju** [comment]
close this in #61
