### ISSUE TITLE
Travis CI on master failed

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-incubator/cri-tools#83]
See https://travis-ci.org/kubernetes-incubator/cri-tools/jobs/226291949.

**Comment by feiskyer** [comment]
> We’re performing a logs database partition maintenance for public repositories from 1:00AM UTC to 4:00AM UTC on April, 27th. 

Travis is under maintenance, no logs could be seen now.

**Comment by xlgao-zju** [comment]
I met this issue several times, and all caused by attach test. All in the tip version of golang, and time out of [this line](https://github.com/kubernetes-incubator/cri-tools/blob/master/pkg/validate/streaming.go#L209).

**Comment by feiskyer** [comment]
The above test is failed because of exec stream timeout.

![1](https://cloud.githubusercontent.com/assets/676637/25604896/d5f10122-2f39-11e7-8f67-e02e4fb09de1.png)
