### ISSUE TITLE
crictl: add logs command

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-incubator/cri-tools#88]

**Comment by heartlock** [comment]
@feiskyer Please provide more detail description.

**Comment by feiskyer** [comment]
Same with kubectl logs, e.g. `crictl logs --follow=true containerID`

**Comment by heartlock** [comment]
Wait for https://github.com/kubernetes/kubernetes/pull/45580

**Comment by feiskyer** [comment]
@heartlock kubernetes/kubernetes#45580 has been in.
