### ISSUE TITLE
[crictl]Plans to support yaml format podsandbox/container spec?

### ISSUE THREAD

**Issue by Crazykev** [kubernetes-incubator/cri-tools#93]
crictl is designed for CRI general debugging purpose, json format is less easy to read/write for human, is there any plan to support yaml format in run podsandbox or create container related command?

**Comment by feiskyer** [comment]
Yep, that's the plan (see [here](https://docs.google.com/presentation/d/1VM4Tx85ffYZl_VOnBuxN1VQ-RhiM8PSg0gt_D1mP2-0/edit#slide=id.g2190bd8ede_0_67)). Also we could support output formats, e.g. json and yaml.
